# Generated by Django 5.1.4 on 2025-01-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
