# Generated by Django 5.1.4 on 2025-01-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='povod',
            field=models.URLField(blank=True, null=True),
        ),
    ]
